### ISSUE TITLE
Help needed with MFA code

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#1170]
hi @greenape im trying to use your mfa code in my personal project. But i got issue with `@hybrid_property`. `key.decode()` function 
```python
    @hybrid_property
    def secret_key(self):
        import pdb; pdb.set_trace()
        key = self._secret_key
        # key = 'gAAAAABdWAGGpY4vU1yiHmXwZxxVklymH5W30AoFpGdThuFf-33PxCAvKJ7hyljOxye-y2cqk4iTmb4ZzHXNf5LhyqYuf4irnjAB_CP9W4t5ftZ1Oj37nOA='
        try:
            key.decode()
            # *** AttributeError: 'str' object has no attribute 'decode'
        except AttributeError:
            return key
            # return 'gAAAAABdWAGGpY4vU1yiHmXwZxxVklymH5W30AoFpGdThuFf-33PxCAvKJ7hyljOxye-y2cqk4iTmb4ZzHXNf5LhyqYuf4irnjAB_CP9W4t5ftZ1Oj37nOA='
        return get_fernet().decrypt(key).decode()
```

and in another place

```python
    def validate(self, code: str) -> bool:
        current_app.logger.debug(f"Verifying {code} using {self.secret_key}")
        is_valid = pyotp.totp.TOTP(self.secret_key).verify(code)
        # -> Error: binascii.Error: Non-base32 digit found
        if is_valid:
            if (
                self.last_used_two_factor_code == code
            ):  # Reject if the code is being reused
                raise Unauthorized("Code not valid.")
            else:
                self.last_used_two_factor_code = code
            db.session.add(self)
            db.session.commit()
            return True
        else:
            raise Unauthorized("Code not valid.")
```
Can you please help?

_Originally posted by @hprobotic in https://github.com/Flowminder/FlowKit/pull/956#issuecomment-522240199_

**Comment by greenape** [comment]
(Moved over from the original PR)

Hi @hprobotic - basically the issue is that `self._secret_key` should be `bytes`, because that's what the `Fernet` object's `encrypt`/`decrypt` methods expect and return. Looks like in your case it has somehow ended up as a string, so it isn't getting decrypted as it should and hence the binascii error in `validate`.

But with that said, we (I, looking at the git blame) have written some weird juju here to make `TwoFactorAuth.secret_key` behave differently to `two_factor_auth_object.secret_key`.

But I can't immediately think _why_! I've also done this in a couple of other places in the same file, for equally mysterious reasons :confused:

**Comment by greenape** [comment]
Ah, no, I do remember why this is so - it means you can use these properties in filtering expressions. This isn't really necessary in any of these cases though, so they could be demoted to regular `@property`s I think, which would fix your case as well.

**Comment by hprobotic** [comment]
Hi @greenape 
Thanks you so much, I will try to test it in my code. Im not sure that's any difference behaviour between Postgres and Mysql on that or not
Will confirm with you if that work

**Comment by hprobotic** [comment]
And i also found another issue with insert `two_factor_auth` to database

This code block in `user_setting.py`

```python
    auth = TwoFactorAuth(user=current_user)
    auth.secret_key = secret

    auth.validate(code)
    auth.enabled = True
    db.session.add(auth)
```

and `validate()` function declared:
```python
      def validate(code: str) -> bool:
        if is_valid:
            if (
                self.last_used_two_factor_code == code
            ):  # Reject if the code is being reused
                raise Unauthorized("Code not valid.")
            else:
                self.last_used_two_factor_code = code
            db.session.add(self)
            db.session.commit()
            return True
        else:
            raise Unauthorized("Code not valid.")
```

So when execute. At beginning when user try to confirm two_factor, there is a database insertion conflict.
`auth` object already inserted to database during validate. Then after that when we try to update auth enabled attribute and insert again:
```python
 auth.validate(code)
 auth.enabled = True
 db.session.add(auth)
```
That will throw error. because auth object already gone

**Comment by greenape** [comment]
Hi @hprobotic 
I've made some changes which I'm hoping will resolve this in 4c963f16
