### ISSUE TITLE
And i also found another issue with insert `two_factor_auth` to database

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#1173]
And i also found another issue with insert `two_factor_auth` to database

This code block in `user_setting.py`

```python
    auth = TwoFactorAuth(user=current_user)
    auth.secret_key = secret

    auth.validate(code)
    auth.enabled = True
    db.session.add(auth)
```

and `validate()` function declared:
```python
      def validate(code: str) -> bool:
        if is_valid:
            if (
                self.last_used_two_factor_code == code
            ):  # Reject if the code is being reused
                raise Unauthorized("Code not valid.")
            else:
                self.last_used_two_factor_code = code
            db.session.add(self)
            db.session.commit()
            return True
        else:
            raise Unauthorized("Code not valid.")
```

So when execute. At beginning when user try to confirm two_factor, there is a database insertion conflict.
`auth` object already inserted to database during validate. Then after that when we try to update auth enabled attribute and insert again:
```python
 auth.validate(code)
 auth.enabled = True
 db.session.add(auth)
```
That will throw error. because auth object already gone

_Originally posted by @hprobotic in https://github.com/Flowminder/FlowKit/issues/1170#issuecomment-522508877_

**Comment by greenape** [comment]
Hi @hprobotic, thanks for the report! 

I think I see what you mean - bad place for that logic to be really. I haven't encountered this actually raising an error though. But, we aren't testing against MySQL, so possible it causes an issue there.

Have you got a minimal example which causes an error by any chance?

**Comment by greenape** [comment]
Gave this a bit more thought. I think the _right_ solution here is to bump the last used code portion out of the database, and use [dogpilecache](https://dogpilecache.sqlalchemy.org) or similar to handle tracking the last used codes. That should allow us to avoid the scenario described here, and also allow for a ttl on the last used codes, _without_ causing us issues because of our use of uwsgi.

**Comment by hprobotic** [comment]
Yeah, but i think will be better if we can add auth 1 time only. Inside validate function or in user_settings.py.
