### ISSUE TITLE
Add distance matrix as a core table?

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#1271]
For discussion - should we add a (cell) distance matrix as a core table?

Pros: potentially significant speed boost to any cell/tower-distance metrics (e.g. displacement, radius of gyration, contact reference location stats)
Cons: pretty big table

**Comment by maxalbert** [comment]
I'd say it's certainly worth investigating. Quite possible that there are signification speedups. On the other hand, given the size of the table (I estimate a few GB for a couple of 10.000 cells?) we should check that these are not balanced out by I/O overheads. Also, some more advanced metrics might not use cell-to-cell distances but rather cell-to-arbitrary-location distances (although this table might still be useful to cache the underlying cell-to-cell distances).

**Comment by greenape** [comment]
Might be better off with the _site_ distance matrix actually, which will typically be quite a bit smaller.

**Comment by greenape** [comment]
Or even just the point geoms, come to that.
