### ISSUE TITLE
FlowETL unit and integration tests should live closer together

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#1292]
Currently the FlowETL unit and integration tests live in the following folders:
```
flowetl/etl/tests/
flowetl/tests/integration/
```
This is a little confusing and it would be better to have them all in the `tests` subfolder, e.g.:
```
flowetl/tests/unit/
flowetl/tests/integration/
```

**Comment by greenape** [comment]
Closed via #1827
