### ISSUE TITLE
Upgrade FlowDB to Postgres 12

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#1396]
Postgres 12 was [released](https://www.postgresql.org/docs/12/release-12.html) last week and FlowDB should be upgraded to use it because it contains a number of useful improvements (see [release notes](https://www.postgresql.org/docs/12/release-12.html)).

Before we can do this, though, I think we need to wait until compatible PostGIS packages have been released for Debian (unless there is a custom apt repository that I'm unaware of)?

**Comment by greenape** [comment]
Waiting on new packages at the pgdg’s apt repo for:

- [ ] pgrouting
- [ ] postgis
- [ ] pgcron

**Comment by greenape** [comment]
Looks like we're just waiting on pg-cron now. The postgis version is rc2, a bump to plpython 3 has been required as well (probably a good thing from our pov should we ever use it anyway).

We could also consider dropping pg_cron at this point - we don't actually use it!
