### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#1411]
Python 3.8 is out. There's no huge rush to update, I think, from our perspective, but to do so we need to:

- [ ] Update and relock all pipfiles 
     - [x] `flowkit_jwt_generator/Pipfile`
     - [ ] `flowdb/testdata/synthetic_data/Pipfile`
     - [ ] `flowdb/testdata/test_data/Pipfile`
     - [ ] `flowdb/Pipfile`
     - [x] `integration_tests/Pipfile`
     - [ ] `flowetl/Pipfile`
     - [x] `flowmachine/Pipfile`
     - [x] `docs/Pipfile`
     - [x] `deployment/Pipfile`
     - [x] `flowapi/Pipfile`
     - [x] `flowclient/Pipfile`
     - [x] `flowauth/Pipfile` (this one might be blocked for a while - still at 3.6 because of uwsgi + alpine)
- [ ] Add or modify `python_requires=` in all `setup.py` files
     - [x] `flowkit_jwt_generator/setup.py`
     - [x] `flowetl/etl/setup.py`
     - [x] `flowmachine/setup.py`
     - [x] `flowapi/setup.py`
     - [x] `flowclient/setup.py`
     - [x] `flowauth/backend/setup.py`
- [x] Update the circle config
- [x] Switch travis testing for flowclient on 3.8-testing to 3.8
- [ ] Update all Dockerfiles
     - [ ] `flowdb/testdata/Dockerfile.synthetic_data`
     - [ ] `flowdb/testdata/Dockerfile`
     - [ ] `flowdb/Dockerfile`
     - [ ] `Dockerfile`
     - [ ] `flowetl/Dockerfile`
     - [ ] `flowetl/deployment_example/ingestion_db/Dockerfile`
     - [x] `flowmachine/Dockerfile`
     - [x] `flowapi/Dockerfile`
     - [x] `flowauth/Dockerfile`

**Comment by maxalbert** [comment]
Gave this a quick try and AFAICT `numpy` doesn't currently have a wheel released for python 3.8, so the docker image build for `flowmachine` will fail because `python:3.7-slim` doesn't include any of the dev libraries needed to build numpy from source. So probably best to wait until a wheel is available to avoid extra work or bloating the docker image.
