### ISSUE TITLE
FlowMachine failed to start

### ISSUE THREAD

**Issue by uwu666-ui** [Flowminder/FlowKit#1472]
**Describe the bug**
FlowMachine failed to start :( Please open an issue at https://github.com/Flowminder/FlowKit/issues/new?template=bug_report.md&labels=FlowMachine,bug including the output of running 'docker logs flowmachine'

**Product**
FlowMachine failed to start

**Version**
Version(s) of the product affected.

**To Reproduce**
 bash <(curl -s https://raw.githubusercontent.com/Flowminder/FlowKit/master/quick_start.sh)
Starting containers (this may take a few minutes)
Pulling flowdb                   ... done
Pulling flowauth                 ... done
Pulling flowapi                  ... done
Pulling flowmachine_query_locker ... done
Pulling flowmachine              ... done
Creating network "flowkit_qs_db" with the default driver
Creating network "flowkit_qs_flowetl_db" with the default driver
Creating network "flowkit_qs_redis" with the default driver
Creating network "flowkit_qs_default" with the default driver
Creating network "flowkit_qs_zero" with the default driver
Creating flowmachine_query_locker ... done
Creating flowauth                 ... done
Creating flowdb                   ... done
Creating flowapi                  ... done
Creating flowmachine              ... done
Waiting for containers to be ready..
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - no response
Waiting 10s
127.0.0.1:5432 - rejecting connections
Waiting 10s
127.0.0.1:5432 - accepting connections
FlowDB ready.
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
/dev/fd/63: line 141: netstat: command not found
Waiting 10s
FlowMachine failed to start :( Please open an issue at https://github.com/Flowminder/FlowKit/issues/new?template=bug_report.md&labels=FlowMachine,bug including the output of running 'docker logs flowmachine'

**Comment by greenape** [comment]
Thanks for the report!

Looks like my assumption that the `netstat` command is available everywhere is incorrect! Would you mind sharing what operating system you were using?

**Comment by uwu666-ui** [comment]
I am using debian 9 stretch

**Comment by greenape** [comment]
Thanks. Is the `ss` command available on your system?

**Comment by greenape** [comment]
I'm hoping that `bash <(curl -s https://raw.githubusercontent.com/Flowminder/FlowKit/44ea46ba5b5c8967e8aa4733293854e20e97309b/quick_start.sh)` will work as expected on your system, would be great if you could give it a try and let us know if it resolves the issue :)
