### ISSUE TITLE
FlowETL sensor has no schedule

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#1529]
The FlowETL sensor dag has no schedule interval, which means that it has to be run manually.

Instead, it should have a _configurable_ sensing interval.

**Comment by chrisjbrooks** [comment]
> The FlowETL sensor dag has no schedule interval, which means that it has to be run manually.
> 
> Instead, it should have a _configurable_ sensing interval.

Add initial and incremental load tests to complement this.
