### ISSUE TITLE
Pin deps in AutoFlow Dockerfile

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#1582]
The versions of dependencies installed in `autoflow/Dockerfile` are currently unpinned. These should be pinned.

**Comment by greenape** [comment]
Suspect the tricky thing with this will be that it includes flowclient, so one needs to fiddle with the docker build context.

**Comment by jch1g10** [comment]
#1753 pins the Ruby dependency versions, but Python dependencies are currently still not pinned in the docker image.

**Comment by greenape** [comment]
This is blocked until CircleCI update their available docker versions to include 19.03, which adds support for per-dockerfile docker ignores, at which point we can bump the Dockerfiles up to the root and expand the context.
