### ISSUE TITLE
Unhandled exceptions in the FlowAuth backend do not show in the frontend

### ISSUE THREAD

**Issue by jch1g10** [Flowminder/FlowKit#1639]
When interacting with the FlowAuth UI, an unexpected error in the backend will result in the user getting logged out and redirected to the login screen, but no error dialog will be shown.

It would be useful to display an error dialog when this happens, otherwise it could be unclear to the user whether the action they attempted was successful. I don't think we want to display any details of the error in the UI, just a generic "internal server error" message to make it clear something went wrong.

**Comment by greenape** [comment]
This is #128 I think.
