### ISSUE TITLE
FlowAuth bounces to login in some browsers

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#18]
**Describe the bug**
Under Electron 59, and Firefox 60 (at least on CentOS), FlowAuth bounces back to the login screen as soon as you try to do anything, and then gives a method not allowed error in the console.

**Product**
FlowAuth

**Version**
master

**To Reproduce**
1. Log in using a user account under electron 59

**Additional context**

There are two issues at work here - the first, is that the session cookie isn't getting passed on where it should be, which means that the next call to the backend is unauthorised. The second, is that on a bad login the user is getting inappropriately redirected to `/signin/next?..`, which is an API route, but only which only accepts POST requests.

What should happen is that the session cookie gets passed on, and in the event of the user hitting an endpoint they aren't authorised for, they should get a redirect to `/`.

**Comment by chrisjbrooks** [comment]
Issue re-occurring on FlowAuth login attempts for Firefox 73

**Comment by jc-harrison** [comment]
Issue occurring on Firefox 73 on Windows, but no problems on mac

**Comment by greenape** [comment]
Is this the same issue (method not allowed)? What’s in the console log?

**Comment by jc-harrison** [comment]
Meh, it works today 🤷‍♂

**Comment by greenape** [comment]
Windows ff version updated?

**Comment by jc-harrison** [comment]
Still 73.0
