### ISSUE TITLE
Different environment variables with similar names and same(?) purpose are confusing

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#189]
There are some cases where multiple environment variables are used that appear to control the same thing (although I'm not entirely sure there aren't subtle differences) but have different names. 

The example that I keep stumbling across is `DB_PORT` vs. `FLOWDB_PORT`. Do these have the same purpose? If not, we should clarify and document their meaning and the differences. If yes, can we merge them and only keep one (e.g. the more explicit `FLOWDB_PORT`)?

There may be other environment variables where a similar overlap exists. In any case, it would be helpful to document all relevant environment variables and their meaning.

**Comment by greenape** [comment]
Are there other examples of this, or can we close now that the `DB_PORT`/`FLOWDB_PORT` ambiguity is resolved?

**Comment by maxalbert** [comment]
I think `DB_PORT / FLOWDB_PORT` was the main one. Let's close this for now, we can always re-open if we stumble across other instances.
