### ISSUE TITLE
Queries removed from cache can't be re-stored through the API

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#1898]
**Problem**
The FlowMachine server only calls `store_async` on a query object if no query info lookup exists in redis, but if a query has been previously stored and removed from the cache then it will have a query info lookup but will still need to be stored again.

**Solution**
The server should always call `store_async` - this is safe even if the query is already running or in cache.

**Comment by greenape** [comment]
Safe but slow - preferable would be that the Redis cache either reports the query as unknown once it has been removed from cache, or we use the Redis cache data to only create-and-trigger if necessary.
