### ISSUE TITLE
Allow FlowClient to get tokens directly from FlowAuth

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#1973]
**Is your feature request related to a problem? Please describe.**
The process for supplying a token for a FlowClient connection is a bit unwieldy (either paste in a very long string, or save token to a file and read in).

**Describe the solution you'd like**
It would be nice if FlowClient could fetch a token directly from a FlowAuth API endpoint. FlowAPI can't do this, since the FlowAuth component is designed to be completely isolated from the main FlowKit server (which won't necessarily have an outgoing internet connection). The same is not necessarily true of FlowClient, though, so we could add a `get_token_from_flowauth` function, and add FlowAuth API routes to allow getting tokens without going through the GUI.

This could perhaps work by the user logging in and creating a token _generator_ through the UI (see https://github.com/Flowminder/FlowKit/issues/829), and then tokens could be generated from this generator via a separate API route that FlowClient could access directly.

**Comment by greenape** [comment]
#106

**Comment by jc-harrison** [comment]
Aha! I missed that one. Closing this as it's already covered by #106
