### ISSUE TITLE
Poll subscriber-level queries?

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#2034]
There may be situations where a user would like to be able to poll subscriber-level queries, even though the result can't be retrieved through the API.

The case for running subscriber-level queries is less strong now that the server runs and caches all sub-queries when running an aggregate query, but I can imagine it could still be useful to check whether a component query is already in cache before running a long-running query that depends on it.

This would not be trivial, because there's currently no way to get the query ID for a query spec that can't be run through the API.

**Comment by greenape** [comment]
Related: #1202

**Comment by jc-harrison** [comment]
#1202 comes closer to solving the underlying problem (we'd like to know how long a query will take to run), so I'll close this.
