### ISSUE TITLE
Misleading warnings/errors from quick start script

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#2118]
The output from the quick start script can be misleading, suggesting problems when actually there are none.

Firstly, the synthetic data generation sometimes takes a little longer than 4 minutes, so the quick start script reports that flowdb failed to start when in fact there is no problem. We should increase the timeout sufficiently to avoid this.

Also, docker-compose warns that AUTOFLOW_DB_PASSWORD and FLOWAPI_TOKEN are not set. These are required for the autoflow container, but not for the containers started by the quick start script.

**Comment by greenape** [comment]
First is now fixed, for the second we can either: set the env vars to safe garbage ones, or (probably better) remove autoflow from the base compose file and put it in `docker-compose.autoflow.yml`.
