### ISSUE TITLE
Non-blocking 'get_result'

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#2199]
`APIQuery.get_result` is a blocking method. Would be good to also have a non-blocking version.

**Comment by jc-harrison** [comment]
Related: #1905

**Comment by greenape** [comment]
I think the most sensible way to achieve non-blocking in this context is definitely asyncio, but that will require a parallel client I think - apart from anything else, because to achieve this polling you'd want to use await-able sleep rather than blocking sleep.
