### ISSUE TITLE
Different cache tablename hashes for the same query

### ISSUE THREAD

**Issue by chrisjbrooks** [Flowminder/FlowKit#226]
**Describe the bug**
Lack of string case normalisation for certain function args results in different cache tablename hashes for the same query. Can result in cached tables not being leveraged for later queries .

**Product**
Which part of FlowKit are you reporting an issue with?

**Version**
version 0.0.5 

**To Reproduce**
Capitalise `hours` arg value and compare resulting md5 hashes
```
degree_lower = SubscriberDegree('2016-01-01', '2016-01-03', hours="all")
degree_upper = SubscriberDegree('2016-01-01', '2016-01-03', hours="ALL")
assert degree_lower.md5==degree_upper.md5
```
Note that this behaviour can affect whether cached dependencies of some composite queries are ignored, leading to unnecessary re-computation of those cached queries e.g. [default setting](https://github.com/Flowminder/FlowKit/blob/527aad3fe24ef79f46b205a475e6582d756eb21b/flowmachine/flowmachine/features/subscriber/subscriber_degree.py#L75) for `hours` in SubscriberDegree is `ALL`. For example the cached table for `degree`, will not get reused in the `ParetoInteractions` query where[ it should appear as a subquery](https://github.com/Flowminder/FlowKit/blob/527aad3fe24ef79f46b205a475e6582d756eb21b/flowmachine/flowmachine/features/subscriber/pareto_interactions.py#L87-L94).
```
degree = SubscriberDegree('2016-01-01', '2016-01-03')
degree.store()
p = ParetoInteractions("2016-01-01", "2016-01-03")
p.get_query()
```

**Expected behavior**
The cached tablename hashes for the results of identical queries should match

**Comment by greenape** [comment]
Nice spot, thanks!

Some solutions spring to mind - first one is obviously to just make sure these are a. internally consistent, and b. made consistent or rejected for inconsistency.

Alternatives are to replace the stringy stuff with Enums, or (at least for `all`) to make `None` mean what `all` currently does.
