### ISSUE TITLE
Flowauth demo data doesn't allow token creation due to expired date (redirects to login screen instead)

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#259]
**Describe the bug**
When logging into Flowauth as `TEST_USER` (using the demo data) and attempting to create a new token, clicking on the (expired) date redirects to the log-in screen instead of allowing me to change the date.

**Product**
Flowauth

**Version**
Latest master (e03de7b0f0a3dea3)

**To Reproduce**
1. Start `flowauth` by running`docker run -p 8000:80 -e DEMO_MODE=1 flowminder/flowauth`
2. Navigate to `http://localhost:8000`, where you should be presented with the Flowauth login screen.
3. Log in as `TEST_USER` (with `DUMMY_PASSWORD`)
4. In the panel on the left-hand side, under "My Servers" click on `Aruba`. The screen shows the "Tokens: Aruba".
5. Click on the `+` sign on the right-hand side to begin creating a new token.
6. Note that under "Token Expiry", beneath the box reading "January 1st 12:00 am" there is a red warning saying "Date should not be before minimal date" (see screenshot below). As an aside, this is not very informative from a user's point of view because it's not clear which _year_ the token refers to.
7. Click into the box with the date ("January 1st 12:00 am")
8. Without warning, the screen changes back to the login screen.

**Expected behavior**
Instead of redirecting to the login screen in step 8. above, I should be able to change the date and create the token.

**Screenshots**

Here is a screenshot from step 6. above. When I click into the box with the date, I get redirected to the Flowauth login screen.
<img width="1424" alt="screen shot 2019-01-19 at 10 57 10" src="https://user-images.githubusercontent.com/2692805/51425820-25f24b80-1bd9-11e9-9dcc-e4257caeeca5.png">

**Comment by greenape** [comment]
Proximal cause is that the dates in the demo data weren’t updated from last year. Should probably reframe them all as deltas not absolute dates, to avoid that happening in future.

(Obvs part of the issue here is that our test coverage for the ui is still insufficient.)

**Comment by greenape** [comment]
Is this still an issue?

**Comment by greenape** [comment]
Test data tokens are now expressed as now + delta, so this is no longer the case.
