### ISSUE TITLE
Flowauth should display year (and also seconds and timezone?) in the token expiry date

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#260]
**Describe the bug**
Flowauth does not display the year in the token expiry date, making it impossible to know when exactly a token will expire. Similarly, it would be helpful if it displayed token expiry up to second resolution, and also displayed the timezone (or made it clear that it refers to UTC if that's the case?)

**Product**
Flowauth

**Version**
Latest master (e03de7b0f0a3d)

**To Reproduce**

1. Follow the steps in #259 until step 6.
2. Notice that the token expiry date reads "January 1st 12:00 am".

**Expected behavior**

The token expiry date should read "1st January 2019, 12:00 am" or similar.

In fact, I'd prefer if the information was as comprehensive as possible so I'd like to see second-resolution and timezone information as well.

**Screenshots**

<img width="500" alt="screen shot 2019-01-19 at 11 07 05" src="https://user-images.githubusercontent.com/2692805/51425900-6a321b80-1bda-11e9-9fc2-8fefeb638d2d.png">

**Comment by greenape** [comment]
I _think_ that it shows the year for years other than the current year. Picker is this: https://material-ui-pickers.firebaseapp.com/api/datetimepicker which should allow us to tweak it to show both year and seconds.
