### ISSUE TITLE
Tidy up logic in claims checks

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#270]
The logic in the [check_claims](https://github.com/Flowminder/FlowKit/blob/master/flowapi/app/run_query.py#L13) decorator isn't always clear, and it makes some implicit assumptions that are not evident from reading this piece of code alone.

For example, the logic of the `if` branch in [L58](https://github.com/Flowminder/FlowKit/blob/master/flowapi/app/run_query.py#L58) depends on the fact that either `query_id` or `query_kind` is present, and it's not clear that if this is not the case this is correctly handled.

Would be good to tidy this up and make it easier to read and understand.

**Comment by jch1g10** [comment]
It would also be good to separate the two stages of checking claims: getting the appropriate claim type, query kind etc., and checking against the token. This would simplify the `check_claims` decorator, and reduce code duplication between `check_claims` and ``check_geography_claims`.
