### ISSUE TITLE
QA checks through API

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#2704]
FlowETL populates the `etl.post_etl_queries` with some simple stats on the ingested data, which are very useful for QA checking. It would be useful to be able to access these QA checks via the API.

**Comment by greenape** [comment]
Yes.

What I'm wondering is if there's a case for supporting allowing people access to only a subset of the qa check results, either by the type of check, or the data being checked.

**Comment by jc-harrison** [comment]
Hmm, yes. Controlling access by type of check would be the trickier of the two (at least in terms of auto-generating the permission scopes, because the list of types of check would need to be inferred from FlowETL), but there may be situations where that's desirable. Not sure about access control by event type - we don't currently support restricting anything else by event type, but that's not to say there isn't a case for adding it.
