### ISSUE TITLE
TotalLocationEvents and long time spans

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#3061]
TLE is relatively slow for long time periods, and perhaps more significantly, adding a day to TLE will gain no benefit from a previous TLE query.

I'm wondering if it would be sensible to make TLE recursive, so that for a TLE spanning a week you run TLE(start, stop-1d) and so on.

Alternatively, it might also make sense to internally run TLEs at the day level and combine them (which would mean you get benefit if you _subtract_ a day as well.

**Comment by jc-harrison** [comment]
Yes, I think there are ways we could make this more efficient. Making it recursive as you suggest would help if you're changing the end date but not the start date, but if you change the start date you wouldn't get any benefit. I'd say combining day-level TLEs is likely to be better overall, but it would be useful to do some benchmarking, to compare running day-level TLEs and combining vs a single long-period TLE.

**Comment by greenape** [comment]
Implementation of this would need to consider that 'day' is actually in part defined by the hours param as well - the days being stitched together could be D1 00:00:00 -  D1 23:59:59, but could also be D1 19:00:00 - D2 05:00:00 for example.

**Comment by jc-harrison** [comment]
> Implementation of this would need to consider that 'day' is actually in part defined by the hours param as well - the days being stitched together could be D1 00:00:00 - D1 23:59:59, but could also be D1 19:00:00 - D2 05:00:00 for example.

I don't think the hours param is particularly relevant here - hours will always be within the [start, stop) interval. So e.g. `TotalLocationEvents(start=D1, stop=D1 + 1 day, hours=(19, 5))` would count events across two disjoint intervals [D1 00:00:00, D1 05:00:00) and [D1 19:00:00, D2 00:00:00).

**Comment by greenape** [comment]
True. And I suppose that works even if `stop=D1 + 5 days` or whatever at the top level. I'm thinking about the case where what one really wants it to count overnight events and allocate to the day the night started, but you can always sum two TLE queries to do that really.

**Comment by jc-harrison** [comment]
> True. And I suppose that works even if `stop=D1 + 5 days` or whatever at the top level. I'm thinking about the case where what one really wants it to count overnight events and allocate to the day the night started, but you can always sum two TLE queries to do that really.

Yes, true, that's something we might want to do - but I think separate from this issue because it would be a change from the current TLE behaviour (where `interval="day"` will aggregate per calendar day).

I suppose we'd have a similar consideration if we wanted to allow larger bins (e.g. interval="month" - which some other queries support but TotalLocationEvents doesn't) - if a time bin extends across multiple days, would we want to break down the query differently so that each bin fits within a single sub-query, or still break it down per day and then sum across sub-query results at the end?

**Comment by greenape** [comment]
I reckon you'd still want to decompose to days and build up because of the aforementioned cache stuff
