### ISSUE TITLE
ss used in quick_start.sh not available on MacOS

### ISSUE THREAD

**Issue by geekysquirrel** [Flowminder/FlowKit#3151]
When running FlowKit via the quick_start.sh script, `ss -tuna` is used to check for the status of FlowMachine.

**Version**
c4dc74f2e99224ae9a98f303a61a29b73f075cb4

**To Reproduce**
1. Run quick_start.sh on MacOS

**Expected behavior**
```
[...]
FlowDB ready.
./quick_start.sh: line 141: ss: command not found
[...]
```

**Additional context**
A quick search revealed that `ss` (a `netstat` replacement included in the `iproute` package on linux) is apparently not included in MacOS, allegedly because of dependencies on the linux kernel. Workarounds exist.

**Comment by jc-harrison** [comment]
Hmm. It should already be using a workaround if `ss` is not found - the script actually runs `(ss -tuna || netstat -an)`.

So either we're just not suppressing the error message from attempting to use `ss` (and actually the script carries on fine), or we're not handling the error properly so the workaround never gets tried. Either way something could do with fixing, but with different degrees of severity.

Does the script go on to output "FlowMachine ready" after the error message?

**Comment by geekysquirrel** [comment]
Yes it does, eventually.
