### ISSUE TITLE
make up in general makefile fails

### ISSUE THREAD

**Issue by geekysquirrel** [Flowminder/FlowKit#3154]
**Describe the bug**
Following the instructions at https://flowkit.xyz/developer/dev_environment_setup/ aftersetting the env vars, `make up` should start the containers.
However, flowdb doesn't build.

**Product**
Makefile

**Version**
c4dc74f2e99224ae9a98f303a61a29b73f075cb4

**To Reproduce**
In the main FlowKit directory, run
1. `set -a && . development_environment && set +a`
2. `make up`

**Expected behavior**
```
[...]
E: Version '1.0.12-1.pgdg100+1' for 'postgresql-12-ogr-fdw' was not found
ERROR: Service 'flowdb' failed to build : The command '/bin/sh -c apt-get update         && apt-get install -y --no-install-recommends         postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR=$POSTGIS_VERSION          postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts=$POSTGIS_VERSION         postgresql-$PG_MAJOR-pgrouting=$PGROUTING_VERSION         postgresql-$PG_MAJOR-ogr-fdw=$OGR_FDW_VERSION         postgresql-server-dev-$PG_MAJOR=$PG_VERSION         postgis=$POSTGIS_VERSION         && rm -rf /var/lib/apt/lists/*         && apt-get purge -y --auto-remove' returned a non-zero code: 100
make: *** [flowdb-build] Error 1
```

**Comment by greenape** [comment]
Looks like we need to bump the version to `1.0.12-2.pgdg100+1`. The pgdg apt is _fanatical_ about only keeping the most current version.
