### ISSUE TITLE
'cdr_type' macro not working in FlowETL QA checks

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#3479]
The if/else block in the 'count_duplicates' and 'count_duplicated' QA check templates is always rendered as an empty string, regardless of the value of the `cdr_type` argument to `create_dag`.

https://github.com/Flowminder/FlowKit/blob/dd3bac2505c04ceb60a26f8cc5cc1d82a3d9babe/flowetl/flowetl/flowetl/qa_checks/qa_checks/count_duplicates.sql#L5

**Comment by greenape** [comment]
Should be params.cdr_type, I think?

**Comment by greenape** [comment]
Will also apply to count_msisdns.

**Comment by greenape** [comment]
I think obvious thing to do would be to add `cdr_type` here: https://github.com/Flowminder/FlowKit/blob/dd3bac2505c04ceb60a26f8cc5cc1d82a3d9babe/flowetl/flowetl/flowetl/mixins/table_name_macros_mixin.py#L28 ?
