### ISSUE TITLE
FlowETL doesn't pick up custom QA checks

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#3484]
I have tried adding a custom QA check template in '<dag_folder>/qa_checks/', as indicated in the `get_qa_checks` docstring, but it doesn't get added as a QA check task.

As a workaround, it would be useful to add a `template_searchpath` parameter to `create_dag`, so that the path to QA check templates could at least be manually added.

**Comment by greenape** [comment]
Hmm. Looks like we're trying to include these on the assumption that airflow rolls in the dag automatically to the template env, which it _does_ but at the point of there being a DagRun, not at the point of there being a dag - so when we call `dag.template_searchpath` as part of our dag creation, the dag folder isn't included.

**Comment by greenape** [comment]
Looks like we should explicitly add `airflow.settings.DAGS_FOLDER` to the list we search, but would also make sense to allow adding additional search paths.
