### ISSUE TITLE
Refactor subsetting logic

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#374]
The subsetting logic currently lives in `EventTableSubset`. The `._make_query()` method manually tweaks the SQL code to apply a subset, but this is done in a fairly ad-hoc way for each of the supported kinds of subsets, and it is mixed with other logic (e.g. temporal filtering). This should be broken out.

**Comment by greenape** [comment]
(Also the two subset factories, for subsets not covered by dates/subscribers)
