### ISSUE TITLE
Recursive formatting in WrappingSQLMixin

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#3841]
I'm experiencing a strange issue with FlowETL, where an operator that uses `WrappingSQLMixin` appears to be executing `prepare_template` multiple times, so the sql string gets recursively wrapped multiple times.

E.g. in a `CreateStagingViewOperator` task, the wrapper sql `CREATE OR REPLACE VIEW {{{{ staging_table }}}} AS {sql}` ends up as:
```
CREATE OR REPLACE VIEW {{ staging_table }} AS CREATE OR REPLACE VIEW {{ staging_table }} AS CREATE OR REPLACE VIEW {{ staging_table }} AS
SELECT * FROM {{ source_table }}
WHERE datetime >= '{{ ds }}'
    AND datetime < '{{ tomorrow_ds }}'
```

I haven't worked out under what circumstances this happens - it's not reproducible, and I suspect stems from Airflow re-running something if it fails initially.

Ideally the solution would be to ensure that `prepare_template` is idempotent, but we'll need to figure out how that's possible within Airflow's template-rendering process.

**Comment by greenape** [comment]
How weird.. Which version of flowetl?

**Comment by jc-harrison** [comment]
I've found the root of the problem - I was defining dags like so:
```
for cdr_type in cdr_types:
    dag_id = f"my_dag_{cdr_type}"
    dag = create_dag(dag_id=dag_id, ...)
    globals()[dag_id] = dag
```

The final dag is picked up by Airflow twice, because it's defined in the variable `dag` _and_ in `globals()[cdr_type]`, and (slightly surprisingly) Airflow's response is to create one dag but render its templates twice. Using a variable name other than `dag` inside the loop fixes this.

Would still be nice to have an idempotent `prepare_dag` (although I'm not sure that's possible in this case), but it's not an issue as long as the dags are defined correctly.

**Comment by jc-harrison** [comment]
For reference, this is FlowETL 1.15.0
