### ISSUE TITLE
Connection should be passed into flowmachine query classes

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#391]
Closely related to #391, the query classes should be refactored so that the flowdb connection is passed into them, rather than the connection being instantiated globally and accessed through `Query.connection`. This would have the advantage that we can more easily pass a dummy connection during tests, and hopefully allow creating query objects without a active connection.

**Comment by greenape** [comment]
I'm thinking about this one again (it bugs be to have not resolved it).

So at a highish level the options I see are: 
1. Require db, redis and thread pool to be passed into all Query objects at instantiation
2. Require whichever of these to be passed into any method that needs them
3. Put all of them on an alternative global singleton object somewhat like the way flask handles request, app etc.

3 definitely feels _easiest_ in terms of the refactoring, and still opens up some possibilities in terms of easier testing and using multiple connections.
