### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#396]
This is a medium-to-longer-term issue, but it will be useful to keep at least two versions of the docs, corresponding to "stable" (= latest release) and "dev" (= current master). Ideally we will also maintain archived versions corresponding to each release, similar to pandas, numpy, etc.

**Comment by greenape** [comment]
There's a MkDocs plugin that handles docs versioning - https://github.com/jimporter/mike but we would need to add support to the theme we currently use for the docs: https://github.com/jimporter/mike/issues/10

**Comment by greenape** [comment]
Looks like this is now possible with mike+material.

**Comment by greenape** [comment]
https://github.com/squidfunk/mkdocs-material-example-versioning
