### ISSUE TITLE
API route to check that flowapi is up and running

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#398]
In order to check whether flowapi is up and running it would be useful to have a minimal "ping" route, which replies basically with "yes, I am up and running".

For further diagnostics it might be useful to also allow querying whether flowapi is successfully connect to flowapi and/or flowdb.

**Comment by greenape** [comment]
This exists, insofar as the bare URL will return a 200, but should probably provide a little more than that.

**Comment by josh-gree** [comment]
Thinking more something that exercises all the different connections. So hit api and then api -> fm -> db  -> fm -> api?

**Comment by josh-gree** [comment]
Without the need to generate a token or have data in the DB...

**Comment by greenape** [comment]
Something like that, yeah. This might actually be multiple endpoints though - one for 'hi, yep, I'm here and I am flowapi', one for 'ping everything', and one last one for 'I'm API vx, talking to fm vy, and db vq'?

**Comment by greenape** [comment]
I'm inclined to think that you should not need a token for a hello, should for triggering a ping, and in two minds about the versions.

**Comment by josh-gree** [comment]
Why for a ping?

**Comment by greenape** [comment]
Worth noting here that getting a bare 200 from flowapi means Flowmachine and FlowDB are available.

**Comment by greenape** [comment]
I'm closing this, because I feel the 200 is sufficient at this time.
