### ISSUE TITLE
Additional flowdb aliases and port configuration in docker-compose-dev.yml

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#409]
Another tweak is needed for the flowdb aliases in the dev setup.

In 99% of the use cases we only want to spin up one of the available flowbd instances (`flowdb`, `flowdb_testdata`, `flowdb_synthetic_data`). In this case whichever one is being used should be available under the alias `flowdb`.

However, _if_ someone wants to spin up more than one at the same time these should be available under different aliases, and on different ports. So we should add these extra aliases to `docker-compose-dev.yml` and also call the environment variables controlling these ports differently (currently they are all called `FLOWDB_PORT`).

I'm wondering whether we should rename the service that's currently called `flowdb` to something like `flowdb_bare` to indicate that it doesn't contain any data, and to put it on equal footing with `flowdb_testdata` and `flowdb_synthetic_data`?

**Comment by jch1g10** [comment]
Yes, I'd be in favour of renaming the service `flowdb` to `flowdb_bare` or `flowdb_empty` or something similar.

**Comment by josh-gree** [comment]
An example of how dev and prod are very different. I don't feel it makes sense to try to construct a dev setup that is so comprehensive that a subset of it is the prod setup. We should seperate the setups.

**Comment by josh-gree** [comment]
Also the empty `flowdb` is `flowdb` so it should remain called that.  A DB with data inside is not the product we are producing - `flowdb_bare` makes it sound less than what it is...

**Comment by maxalbert** [comment]
I don't understand your comment about dev and prod. When I talked previously about keeping dev and prod in sync I didn't mean that prod should be a _subset_ of dev (and this is reflected in the fact that we have two different docker-compose files for both). Rather, that the way in which they are set up and controlled are the same (e.g. the only difference being configuration options controlled via environment variables). See the [Twelve-Factor App](https://12factor.net/) principles. Does this differ from how you think about it?

**Comment by maxalbert** [comment]
Re `flowdb_bare`, it would only be the docker _service_ that would be called that. In that sense it's like a variable name, so why not give it a meaningful name that reflects how it differs from the other ones? 

(As an aside, in the integration tests docker-compose file the redis container is called `query_locker` instead of `redis`; strangely, I also sometimes have an urge to rename this to `redis`, but when I stop to think about it the name `query_locker` is definitely more descriptive - "redis" just tells you what it is, not what it is being used for).

**Comment by greenape** [comment]
Is this resolved by #610?
