### ISSUE TITLE
Revisit built in FlowDB roles and groups

### ISSUE THREAD

**Issue by josh-gree** [Flowminder/FlowKit#410]
We have two roles within `flowdb`:

- `analyst`
- `reporter`

These names made more sense in the past - currently `analyst` seems to be the `flowmachine` user and `reporter` seems to be the `flowapi` user.  I think we should change the names.

**Comment by maxalbert** [comment]
Are these roles even actively used at the moment? And if so, are they used in a sensible way? I get the feeling that there is some legacy around them and that it might be good to double check whether they are actually needed - and if so, to tidy up (and test) the exact permissions they should have.

**Comment by josh-gree** [comment]
They are used and the use does make sense. The api only needs read access thus connects as the `reporter` role whereas `flowmachine` needs write access and so connects with the `analyst` role. They are just badly named roles...

**Comment by maxalbert** [comment]
Do you have a suggestion for more sensible names?

**Comment by josh-gree** [comment]
Yeah `flowamchine` and `flowapi`

**Comment by gzagatti** [comment]
I would agree with @josh-gree here. When deploying Flowkit components, I am usually confused by the user names, `flowmachine` and `flowapi` might be sensible names to start with. In any case, we might want to consider ways of also creating `flowmachine`-type of users for identifying different analysts. At the moment, I have to create a new user manually.

**Comment by maxalbert** [comment]
Sounds good. These names make it clear that they are specifically meant for flowmachine and flowapi to connect (in particular, intended for machine usage). Human analysts should typically use flowmachine or flowapi anyway rather than connecting directly to the database, not least because of the enhanced audit trail.

**Comment by greenape** [comment]
There’s an overlap between users and groups with roles. How about two _groups_ with nice descriptive names, and two new users (flowmachine and flowapi) that belong to those groups?

**Comment by greenape** [comment]
After a bit more thought, I propose we have _four_ built in users:

- flowdb
- flowmachine
- flowapi
- etl

And slightly more groups, something like:

- geography_read (read access to geography.*)
- raw_data_read (read access to events.*, also a member of geography_read)
- cache_table_read (read access to cache.*)
- etl_read (read access to etl.*)
- etl_write (write access to etl.*)
- cache_table_write (write access to cache.*)
- raw_data_write (write access to events.*, infrastructure.*, geography.*, available_tables)

Which would allow, for example, the user that ETL is run as to have all the necessary write access, but no ability to monkey with other users as is the case if ETL is run as flowdb.

**Comment by josh-gree** [comment]
Sounds good. Not sure why you would want to be able to *just* read the geography tables? Assuming the etl user would be in all groups? It would need to be...

**Comment by greenape** [comment]
Yeah, I'm not saying this is exactly the right division of permissions. My thinking with geo as a distinct one is that you want, for example, flowapi to be able to read cache and geo, but nothing else, but don't necessarily want to grant read on the cache to etl, for example, if it doesn't actually need it.
