### ISSUE TITLE
circleci container images deprecation

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#4638]
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034/3?mkt_tok=NDg1LVpNSC02MjYAAAGBCwaxsiWN98EYFoZZQCsHyK7f1F7MUEnW-ZbAKRebOOs6Tbs5roz-r_ho7l9MtNnIlzJaN92QqUhm3Rm4U-X-wvOxdwxc6sB2oQi5zcQdmXc

Docker images prefixed `circleci/` will cease to work Dec 31 2021, which will break the CI pipeline.

**Comment by Thingus** [comment]
I should probably have asked this before assigning myself, but... is this just a simple ctrl-r for `image: circleci` to `image: cimg`, or is there more to it?
