### ISSUE TITLE
FlowAuth test timeout

### ISSUE THREAD

**Issue by Thingus** [Flowminder/FlowKit#4642]
As the permission space for FlowAPI increases, the FlowAuth end-to-end test is becoming increasingly shaky and slow.

**Product**
FlowAPI test suite

**Version**
1.5 + 

**To Reproduce**
Run `flowauth_end_to_end` after adding new query types

**Expected behaviour**
Test ends in a timely manner (within half an hour), but does not cause failure due to timeout.

**Additional context**
The quick fix is to increase the timeout for Cypress, but this obviously isn't sustainable - do we need to reexamine the testing framework for flowauth?

**Comment by greenape** [comment]
Yes. Yes, it is the _test_ that is the problem. Not the combinatorial explosion in the code I wrote for this 👀 .
