### ISSUE TITLE
Labelled spatial aggregates

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#4668]
Add equivalents of `SpatialAggregate` and `Flows`, which disaggregate counts according to per-subscriber categories defined in a specified sub-query (e.g. `MobilityClassification` - see #4666). The aggregate queries should take a `subscriber_labels` argument in addition to the subscriber-locations queries, join on subscriber, and group by label as well as location.

In the case of `Flows`, we could consider allowing two separate sets of labels (i.e. subscribers labelled differently at the "from" and "to" locations). It's not clear whether that would be useful in practice, though (and if it was, the same could be achieved by using a single `subscriber_labels` query that assigns a label-pair to each subscriber), so in the first instance a single set of labels should be sufficient.

This could be achieved using new classes `LabelledSpatialAggregate` and `LabelledFlows`, or by adding an optional `subscriber_labels` parameter to the existing `SpatialAggregate` and `Flows` classes.

**Comment by greenape** [comment]
Is this more generally applicable than these two classes? i.e. all of the od variants (ex: trips, consec, meaningful locations), and all aggregates to a location (ex: TLE, unique subs, unmoving counts, introversion etc.)?

**Comment by jc-harrison** [comment]
> Is this more generally applicable than these two classes? i.e. all of the od variants (ex: trips, consec, meaningful locations), and all aggregates to a location (ex: TLE, unique subs, unmoving counts, introversion etc.)?

Yes, I suppose this could apply to all aggregates (at least, all aggregates over subscribers - which is just about everything except TotalNetworkObjects, I think).

**Comment by jc-harrison** [comment]
Closely-related issue: https://github.com/Flowminder/FlowKit/issues/2023
