### ISSUE TITLE
Integration tests fail with default flowdb/redis port values in .env file

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#467]
The `integration_tests/.env` file contains the following default values:
```
FLOWDB_PORT=9997
REDIS_PORT=9996
```
These are different to the default values in the toplevel `docker-compose-dev.yml` file (where the values are `FLOWDB_PORT=9000` and `REDIS_PORT_6379`, respectively). As a consequence, the integration tests fail when run against the default local dev setup.

To reproduce:
```bash
$ make flowdb_testdata-up redis-up
$ cd integration_tests/ && pytest -x tests/flowmachine_tests/
```
Error:
```
Traceback (most recent call last):
[...]
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 9997?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 9997?
```

The most immediate fix I can think of is to change the values in `integration_tests/.env` to 9000 and 6379 (or to remove these vars from that file altogether and force the user to set them explicitly if flowdb/redis are not running on the default ports).

However, it is slightly annoying that the docker-compose file and the `.env` file can get out of sync with each other. Ideally these defaults should only be configured in a single place, but I can't see where this would be.

**Comment by greenape** [comment]
There's a totally separate compose file for the integration tests, and a script for running them (`cd integration_tests && pipenv run run-tests`). The different values in the `.env` are actually there to avoid colliding with any other running flowdb & Redis instances, but I'm definitely up for a better solution here.

**Comment by maxalbert** [comment]
Well, I've been thinking for a while that the integration tests should really use the toplevel docker-compose file anyway (and we should remove the one in that folder). This would have the added benefit that this docker-compose file works as expected.

I don't really see any potential for conflict with already running flowdb/redis instances. During the CI process you only have one instance (which would be spun up with the default port values), and locally you typically want to test against the running instances anyway (and if not you can always spin up new instances using the toplevel docker-compose file by passing different env vars).
