### ISSUE TITLE
Add redacted forms of labelled SpatialAggregate/Flows

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#4671]
The disaggregated forms of `SpatialAggregate` and `Flows` described in #4668 may need a slightly different approach for redaction, because in some cases individual per-category counts that are redacted could be inferred by comparing the remaining unredacted counts to the results of the equivalent non-disaggregated query.

One approach could be to drop the labels (and return a single, non-disaggregated count) for each location where any of the disaggregated counts are too small.

**Comment by Thingus** [comment]
Already exists for SpatialAggregate in #4668 - will see similar for #4696
