### ISSUE TITLE
`available_dates` should return a dict with keys for all possible types of data

### ISSUE THREAD

**Issue by josh-gree** [Flowminder/FlowKit#47]
**Describe the bug**
If FlowDB only contains only `voice` data then the `available_dates` function will return a dict with only a `voice` key. 

**Product**
FlowDB and FlowMachine

**Version**
Master

**Expected behavior**
`available_dates` should return a dict with keys for all possible types of data that can be ingested into FlowDB. For those data types for which no data has been ingested the associated value should be an empty list.

**Comment by greenape** [comment]
This is referring to `Connection.available_dates`, and s/`voice`/`calls`?

This method requires you to specify the tables you want to check against - the default check is relatively expensive at the moment, so checking for _all_ available dates against all tables isn't I think desirable as the default.

You can use it in combination with the `available_tables` property of the `Connection` to check everything available on that DB instance though.

I'm also aware from @gzagatti that there's a bug in that the `available_dates` method _should_ allow you to pass in a list, but actually doesn't. Will open a separate issue for that.

**Comment by josh-gree** [comment]
On an empty DB

```
In [1]: import flowmachine as fm

In [2]: con = fm.connect()
/usr/local/lib/python3.6/site-packages/flowmachine/core/connection.py:122: UserWarning: Maximu
m number of connections (pool size + overflow = 6) is greater than the available cpu cores (4)
.
  + "greater than the available cpu cores ({}).".format(os.cpu_count())
FlowMachine version: 0.0.3+21.g9c93d14
Flowdb running on: flowdb:5432/flowdb (connecting user: flowdb)

In [3]: con.available_dates(table='all')
Out[3]: {}
```

**Comment by greenape** [comment]
Ah, ok, I see.

The reason they don't show up isn't because there's no data, the reason they don't show up is because there's nothing to say what _kind_ of data they're going to contain - of particular relevance for the _rest_ of flowmachine is that until you specifically say the tables are going to contain subscriber data, there's no way to know that.

So, defaulting to returning info about tables which might _not_ contain info about subscribers is not the behaviour that the rest of the codebase is expecting, which is going to lead to unforeseen consequences.

If you _really_ want this behaviour, you can do this:

```python
con = flowmachine.connect()
tables, has_locations, has_subscribers, has_counterparties = zip(*con.available_tables)
con.available_dates(table=tables)
```

The way this method and related ones behave are likely to change quite soon once there's a more robust ETL metadata setup in place.

**Comment by josh-gree** [comment]
Yeah I don't understand what you mean. In what situation would `mds`, `calls`, `sms`, `forwards` or `topups` not contain "subscriber" data?

**Comment by greenape** [comment]
Totally possible that these would contain no data in the msisdn, imei etc. fields, if, for example pseudonymisation was felt to be insufficient, in the same way that location information could be omitted.

**Comment by josh-gree** [comment]
If that's the case we still have data, however minimal, for those dates and I would expect  `available_dates` to tell me that. How else would I find that out?

**Comment by greenape** [comment]
Name the table(s) you want to check. I get that this isn't the default behaviour you want, but it is the default behaviour the rest of the codebase currently assumes. 

As I say, it would be reasonable to expect the way this behaves to change quite a lot in the near future as the ETL machinery becomes more concrete and we continue to refactor the internals of FlowMachine, so where possible avoid relying on the internal behaviour of FlowMachine and build against FlowClient instead.

**Comment by josh-gree** [comment]
Ok

**Comment by gzagatti** [comment]
@greenape, given the discussion above how are we supposed to query `flowdb` whether certain dates exist in the database without using `flowmachine` internals and using the provided API? And who is developing the ETL machinery? What will it look like?

Our use case, is to query `flowdb` whether certain dates exists before requesting the calculation of a certain measure. We don't want to submit a large number of requests to the database (let's say for `daily_flows`) when many of those requests are for dates that don't even exist. What we would like to do is:

1. Query whether some dates exist
2. Request the measure for those dates.
