### ISSUE TITLE
Inconsistent param names in FlowClient

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#470]
In flowclient,`location_event_counts` takes an `end_date` argument. `modal_location_from_dates` and the `meaningful_locations_*` functions take a `stop_date` argument.

**Comment by maxalbert** [comment]
I think there is also a similar inconsistency internally in flowmachine, IIRC. Which version should we go for? (My personal preference would be `end_date`.)

**Comment by jc-harrison** [comment]
Re-opening this as more-recently-exposed queries are inconsistent - `subscriber_degree`, `topup_amount`, `event_count`, `displacement`, `pareto_interactions` and `nocturnal_events` all take `start` and `stop` parameters, not `start_date` and `end_date`. `handset` does have `start_date` and `end_date` parameters, but the docstring is inconsistent.
