### ISSUE TITLE
flowmachine should own all cache tables

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#4714]
The flowmachine user in Flowdb needs to be the owner of all cache tables in cache schema, otherwise the flowmachine server will be unable to properly clean the cache and error out in trying to do so. Should either explicitly set the owner of the table to flowmachine user, or, there should be a trigger set in Flowdb to do this.

**Comment by jc-harrison** [comment]
Re-opening because the currently-implemented trigger doesn't actually affect flowmachine-created cache tables, because 'CREATE TABLE AS' (used to store a flowmachine query result) is a different command from 'CREATE TABLE' (for which the trigger is defined).

**Comment by jc-harrison** [comment]
Nope, still not working 🤦 

Looks like it doesn't trigger if the 'CREATE TABLE AS' command is within an 'EXPLAIN' statement...

**Comment by greenape** [comment]
So we can:

- Find another way to trigger this (e.g. on changes to pg_tables?)
- Find another way to collect timing info when creating cache tables (instead of via explain)
- Alter the owner through a non-pg mechanism (e.g. flowmachine should do it)

**Comment by greenape** [comment]
Can't do the first (pg_tables is a view, no triggers allowed on system tables). Issue with the third is that we currently allow different names for the flowmachine user, so you can't arbitrarily assign ownership to `flowmachine`, because that user might not exist.
