### ISSUE TITLE
Inconsistent use of environment variable name for connecting with FlowDB

### ISSUE THREAD

**Issue by gzagatti** [Flowminder/FlowKit#485]
**Describe the bug**
The [`connect`](https://github.com/Flowminder/FlowKit/blob/314caa4a19ccb480abed072a07dd76a1ddbe5ecb/flowmachine/flowmachine/core/init.py) method of `flowmachine` will read the following environment variables to connect to the DB:

- `FLOWDB_PORT`
- `DB_USER`
- `DB_PW`
- `DB_HOST`
- `DB_NAME`
- ...

Now I find it inconsitent to have `FLOWDB_PORT` and the other parameters prefixed with `DB`. Is there any reasons for that? 

**Product**
Flowmachine

**Version**
master branch

**Expected behavior**
Can we perhaps be consistent and use `FLOWDB` as the prefix?

**Comment by maxalbert** [comment]
From @gzagatti: we should also consider renaming the `REDIS_...` env variables to something more meaningful such as `FLOWMACHINE_REDIS_...` (or something shorter).

I'll leave this issue open for the time being until we have also changes this name.
