### ISSUE TITLE
Remove option to configure log directory to conform with twelve-factor-app principles

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#488]
According to the [logs](https://12factor.net/logs) section of the Twelve-Factor-App principles: _"A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles."_

Accordingly, we should remove the option to configure the log directory with the `LOG_DIRECTORY` environment variable within flowmachine and flowapi.

Instead, we should facilitate an easy way to route logs to output files during dev/prod deployment (_These archival destinations are not visible to or configurable by the app, and instead are completely managed by the execution environment."_).

**Comment by greenape** [comment]
Technically, we should also send all logs to stdout and do _no_ level filtering.
I'm a bit conflicted on this, because certainly for library usage of flowmachine you'd probably rather the log level was configurable.
