### ISSUE TITLE
Integration tests should use env vars FLOWAPI_HOST and FLOWAPI_PORT to connect to flowapi

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#493]
The pytest fixture `api_host` in the integration tests currently returns one of the two hard-coded strings `"http://flowapi:9090"` or `"http://localhost:9090"` to determine the url on which flowapi is running. This is a legacy from a while ago and should really use the environment variables `FLOWAPI_HOST` and `FLOWAPI_PORT`.

**Comment by greenape** [comment]
How combining that with bind-to-0 as well: https://stackoverflow.com/questions/1365265/on-localhost-how-do-i-pick-a-free-port-number
