### ISSUE TITLE
Unable to update group permissions in FlowAuth

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#5091]
After uploading a new API spec to an existing server in FlowAuth, I am trying to edit an existing group to grant permissions for the newly-added scopes. I can tick the boxes next to the new scopes, but on attempting to "save" I get signed out and the changes do not take effect.

In the console log I can see that `PATCH https://auth.flowminder.org/admin/groups/4/servers` is returning a 502 error, and there's a message "SyntaxError: Unexpected token < in JSON at position 1". I haven't yet been able to check the server-side logs to investigate further.

**Comment by greenape** [comment]
The cause of this is that we're not awaiting something we should be in the JS, the trigger for it is that the permissions update is taking too long behind the scenes.
