### ISSUE TITLE
Allow adding marshmallow schemas for sub-queries which should not be exposed 

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#525]
Some queries such as meaningful locations are composed of sub-queries that should be cached but that we don't necessarily want to expose.

It would be good if it was possible to add marshmallow schemas for such sub-queries which are not exposed via the API (and not included in the API spec). This would allow to use the marshmallow machinery to construct and cache sub-queries automatically, without the user having to worry about how the toplevel query decomposes into them.

**Comment by maxalbert** [comment]
@greenape I have a feeling this might have been addressed by one of your recent PRs (possibly the spatial aggregates one)?

**Comment by greenape** [comment]
Closing this issue, because I think it is better covered by a more general 'smart scheduling/execution' one to be opened in the next few weeks.
