### ISSUE TITLE
Find an alternative to folium for map embeds

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#528]
Folium, while neat, performs pretty horribly, has issues with chrome and is a bit limited. We should look out for alternatives. One thing to track is this: https://github.com/uber/kepler.gl/issues/331

**Comment by maxalbert** [comment]
Probably worth looking into [GeoViews](http://geo.holoviews.org/). For multiple reasons, not least because it supports animated timelines out of the box.

**Comment by jch1g10** [comment]
For the record, I tried using GeoViews for the maps, but abandoned this due to the complication of installation and difficulty getting the maps to appear in the docs-compiled notebook output.

**Comment by maxalbert** [comment]
For the record, @jch1g10's recent work suggests that Mapbox is the best alternative for our current use case. As a side note, it would be good to briefly document the pros/cons of the various solutions while it's still fresh in memory (possibly in an ADR).

**Comment by jch1g10** [comment]
I'd be happy to document the pros/cons I've found of Folium/GeoViews/Mapbox in an ADR. Where should this live?

**Comment by maxalbert** [comment]
We used to have a folder for ADRs but somehow this seems to have gone awol. Let's re-add this in a separate PR, and then we can add another file in this folder to document this info.
