### ISSUE TITLE
Add API route for location introversion

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#577]
`flowmachine.features.location.location_introversion.LocationIntroversion` should have an exposed API route.

I'm thinking same parameterisation as the other exposed routes - start, stop, aggregation unit + direction, but I'd like direction to be optional with default `both`.

- [ ] Add `LocationIntroversionExposed` class
- [ ] Add marshmallow schema
- [ ] Add schema to `FlowmachineQuerySchema`
- [ ] Add flowclient function
- [ ] Add tests to integration tests
    - [ ] Add test case to `test_get_query_params`
    - [ ] Add test case to `test_run_query`
- [ ] Add query endpoint to Flowauth demo data
- [ ] Update approval test data for integration tests

**Comment by maxalbert** [comment]
Thinking about it, the purpose of the integration tests `test_get_query_params` and `test_run_query` (in the files `integration_tests/tests/flowmachine_server_tests/test_action_get_params.py` and `integration_tests/tests/flowmachine_server_tests/test_action_run_query.py`) is to exercise the respective action handlers but should be agnostic of any specific queries.

Instead, if we want to test the specific queries and their parameters I suggest to add a test to `integration_tests/tests/test_queries.py`, which exercises the individual queries through their respective flowclient functions.

At the moment the test files and test names don't always make it very clear what their purpose is and which parts of the code they are supposed to exercise. We should rename the above ones in particular to clarify this. I have opened #584 to track this.
