### ISSUE TITLE
flowmachine sqlachemy is unpinned

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#5867]
This pr: https://github.com/Flowminder/FlowKit/pull/5864 updated the pin on sqlalchemy to 2.0.3, which should have triggered test failures because of the breaking changes made in sqlalchemy 2.

It didn't, because the version installed by pipenv is actually ignored because of the version specifier being set as <2 in setup.py. That means it gets replaced in the docker image when setup is run, replaced in the tests by the editable dev install of flowmachine, and is correctly pinned in the integration tests because the pin there comes from flowmachine's setup.py

**Comment by jc-harrison** [comment]
I wonder whether the right thing to do here would be to stick `flowmachine = {editable = true, path = "."}` in the non-dev packages section of the Pipfile, and remove (from the Pipfile) all the packages that are specified in the setup.py requirements (which I suppose should be all of them, really) - then we're not duplicating requirements and version pins.
