### ISSUE TITLE
Table aggregates.aggregates is a bad name!

### ISSUE THREAD

**Issue by josh-gree** [Flowminder/FlowKit#587]
Change table name for `aggregates.aggregates` to something more meaningful that reflects its use as a place for storing information about the process of calculating aggregates rather than aggregates themselves.

**Comment by maxalbert** [comment]
Just wondering if we should actually rename the _schema_ rather than the table? We could call it `etl_metadata.aggregates`? @josh-gree will know best how this is likely to fit in with the upcoming ETL changes, and if appropriate we can roll it into one of the next PRs.
