### ISSUE TITLE
Add SpatialAggregate to api

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#599]
Modal locations and daily locations are presently dealt with by calling `aggregate()` on any query created by the api. This _implicitly_ returns them wrapped in `SpatialAggregate`. This should be made explicit, and the hidden call to `aggregate()` removed. This also paves the way for a broader classification of things-that-are-aggregated, which I think might warrant being a marshmallow spec in itself (probably allOf).

- [x] Add marshmallow spec for SpatialAggregate
- [ ] Remove call to `aggregate()`
- [ ] Update client
- [ ] Update claims checking in FlowAPI

**Comment by greenape** [comment]
One thing to consider here is that `modal_location` operates on `daily_location` specs, so this presumably needs to be a separate function in FlowClient. Also means a bare `daily_location` query spec should no longer be allowable, and means any examples using `modal_location` or `daily_location` will need to be updated.

**Comment by greenape** [comment]
#524

**Comment by OwlHute** [comment]
Am I right in thinking the idea is to make this aggregation process user-callable, so an API user can use it more generally on any pair of applicable data sets one of which is a subscriber list, and produce a sort of aggregated "product" of the sets?

**Comment by greenape** [comment]
Think that's in reference to #600 @OwlHute?

**Comment by greenape** [comment]
Yes. The API requests that previously went:

```json
{"query_kind": "daily_location" ...}
```

Should now go:

```json
{"query_kind":"spatial_aggregate", "locations":{"query_kind": "daily_location" ...}}
```

**Comment by OwlHute** [comment]
If that is the only change, it sounds pretty simple. So I'm guessing other changes are also required (including obviously changes to the relevant test cases)

**Comment by OwlHute** [comment]
Following class added in flowmachine/flowmachine/core/server/query_schemas/custom_fields.py, preserving alphabetic order of existing classes:

class SpatialAggregate(fields.List):
    """
    List representing a spatial aggregate subset.
    """

    def __init__(self, required=False, allow_none=True, validate=None, **kwargs):
        if validate is not None:
            raise ValueError(
                "The SpatialAggregate field provides its own validation "
                "and thus does not accept a the 'validate' argument."
            )

        super().__init__(
            required=required, allow_none=allow_none, validate=OneOf([None]), **kwargs
        )

**Comment by greenape** [comment]
Not sure I follow?
