### ISSUE TITLE
Expose AggregateNetworkObjects via api

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#601]
- [x] Refactor `AggregateNetworkObjects` to take `TotalNetworkObjects` as main argument
- [x] Create new marshmallow spec file under `server/query_schemas`
- [x] Add newly created spec to `FlowMachineQuerySchema`
- [x] Add function to `flowclient.client`
- [x] Add function to `flowclient.__init__`
- [x] Add test to `integration_tests/tests/test_queries.py`
- [x] Add `docs/source/4-developer.md` with newly added query

**Comment by OwlHute** [comment]
What parameters are to be exposed for this route in flowclient ?
