### ISSUE TITLE
Expose RadiusOfGyration via api

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#602]
Pending #600 

- [x] Add marshmallow spec for `RadiusOfGyration`
- [x] Add to allowable joined aggregate queries
- [x] Add flowclient function `radius_of_gyration(start, stop, subscriber_subset)`
- [x] Add test to `integration_tests/tests/test_queries.py`
- [x] Add `docs/source/4-developer.md` with newly added query
- [ ] Change returned column name to `value` from `rog` in `RadiusOfGyration` in SQL and `column_names` attribute
- [ ] Update tests using `RadiusOfGyration` to reflect changed column name

**Comment by OwlHute** [comment]
Implemented all required code changes, and down to one test error:

> Aggregation unit must be specified when running a query.. API returned with status code: 400.{'msg': 'Aggregation unit must be specified when running a query.'}

So it looks like the three parameters given above (start, stop, subscriber_subset) should be augmented by something like aggregation_unit ?!

**Comment by greenape** [comment]
`radius_of_gyration` needs to be used in conjunction with `joined_spatial_aggregate`, because it has no inherent spatial unit attached.

**Comment by OwlHute** [comment]
I'm currently testing a couple of small changes which may fix the remaining errror. So please hold off on review for now. I'll let you know when the changes have been pushed ..
