### ISSUE TITLE
Compose version mismatch between main and flowdb

### ISSUE THREAD

**Issue by Thingus** [Flowminder/FlowKit#6065]
Version for docker-compose.yml has been bumped to 3.9, but the rest of the compose files haven't.

**Product**
The Docker Compose

**Version**
1.18.3

**To Reproduce**
Run `make flowdb_synthetic_data-build`

**Expected behavior**
FlowDB container should build smoothly

**Comment by jc-harrison** [comment]
Are you sure the version mismatch is the problem? I agree it would be nice to have consistent compose-file versions, but `make flowdb_synthetic_data-build` works fine for me.

**Comment by Thingus** [comment]
Ah - the version of docker compose in Yum I was using is at 1.18.0, _well_ out of date.
