### ISSUE TITLE
FlowMachine is incompatible with SQLAlchemy 2.0

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#6066]
SQLAlchemy 2.0 dropped support for passing a SQL query as a string directly to `transaction.execute()` - flowmachine does this in numerous places, so is not compatible with SQLAlchemy >= 2.0.

It's quite likely there are other incompatiblities aside from this one - I haven't checked.

**Comment by greenape** [comment]
This is more problematic now, because pandas has dropped support for sqlalchemy < 2
