### ISSUE TITLE
Query retrieved from cache with non-deterministic ID

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#6148]
**Describe the bug**
Queries are pickled and stored in FlowDB when query results are stored in the cache. This means that a query object can be retrieved by ID, which happens for example when shrinking the flowmachine cache. However, it appears the retrieved query object may have the wrong ID, which can prevent the cache record from being removed.

**Product**
flowmachine/flowdb

**Version**
1.18.4

**Example**
I have encountered the following:

```sql
SELECT query_id, version, class, schema, tablename, table_size(tablename, schema) as table_size
FROM cache.cached
WHERE cached.class!='Table' AND cached.class!='GeoTable'
AND NOW()-created > INTERVAL '43200 seconds'
ORDER BY cache_score(cache_score_multiplier, compute_time, table_size(tablename, schema)) ASC
LIMIT 1;
```

|             query_id             | version |        class        | schema |             tablename             | table_size |
|----------------------------------|---------|-------------------------------|--------|-----------------------------------|------------|
| a22c3b9aba9a20d0bb1ffe71596c76b6 | 1.18.4  | EventCount          | cache  | xa22c3b9aba9a20d0bb1ffe71596c76b6 |  412745728 |

```python
>>> query_obj = fm.core.cache.get_obj_or_stub(fm.core.context.get_db(), 'a22c3b9aba9a20d0bb1ffe71596c76b6')
>>> query_obj
<Query of type: EventCount, query_id: 'd635a943f10f3bb85c5a9969d57dad9c'>
>>> query_obj.is_stored
False
```

**The ID of the retrieved query is non-deterministic - running `fm.core.cache.get_obj_or_stub(fm.core.context.get_db(), 'a22c3b9aba9a20d0bb1ffe71596c76b6')` a second time produces a query with a different ID.** Perhaps this was already true of the original query before it was written to cache - I don't know.

**Additional context**
This may be relevant to https://github.com/Flowminder/FlowKit/issues/6099 - I'm not sure.

**Comment by jc-harrison** [comment]
Also encountered this with a `RedactedTripsODMatrix` query - in this instance leading to the flowmachine server getting SQL from a query object that thinks it's not stored, thereby preventing the result from being retrieved via FlowAPI.

**Comment by greenape** [comment]
I guess the question is where's the varying id coming from? It seems unlikely at first blush that it is introduced by `RedactedTripsODMatrix` itself, cos that class is crazy simple.

**Comment by greenape** [comment]
Interesting that we don't encounter it more often in that case.. maybe to do with hours?

**Comment by greenape** [comment]
Also, I think this is going to behave in a slightly unexpected way, because the hours are going to be interpreted at spanning multiple days (so this is going to include a timespan of 2300-2300+25hr, I _think_).

**Comment by jc-harrison** [comment]
> Also, I think this is going to behave in a slightly unexpected way, because the hours are going to be interpreted at spanning multiple days (so this is going to include a timespan of 2300-2300+25hr, I _think_).

I think it should be fine in that regard - [hour intervals spanning midnight are split](https://github.com/Flowminder/FlowKit/blob/52a392f6640747b259830cc564d76190bc8a5a19/flowmachine/flowmachine/features/utilities/event_table_subset.py#L111), so the hour subset should compile to
```
(to_char(datetime, 'HH24:MI') >= '23:00' AND TRUE) OR (TRUE AND to_char(datetime, 'HH24:MI') < '00:00')
```

**Comment by greenape** [comment]
After a bit of poking around, I see why this is happening now:

Here are the ingredients to the hash in two identical calls to `EventTableSubset`

```EventTableSubset: columns:['country_code', 'datetime', 'duration', 'id', 'imei', 'imsi', 'location_id', 'msisdn AS subscriber', 'msisdn_counterpart', 'network', 'operator_code', 'outgoing', 'tac']
EventTableSubset: hour_slices:<HourSlice: [HourInterval(start_hour=<flowmachine.core.hour_slice.MissingHourAndMinutesTimestamp object at 0x115d21250>, stop_hour='00:00', freq='day', weekday=None), HourInterval(start_hour='23:00', stop_hour=<flowmachine.core.hour_slice.MissingHourAndMinutesTimestamp object at 0x115d21490>, freq='day', weekday=None)]>
EventTableSubset: hours:[0, 23]
EventTableSubset: sqlalchemy_table:events.calls
EventTableSubset: start:2016-01-01 00:00:00
EventTableSubset: stop:2016-01-02 00:00:00
EventTableSubset: subscriber_identifier:msisdn
EventTableSubset: subscriber_subsetter:<SubscriberSubsetterForAllSubscribers (query_id='869c2093b89e9809c7656dd19ae718ba')>
```

and..

```EventTableSubset: columns:['country_code', 'datetime', 'duration', 'id', 'imei', 'imsi', 'location_id', 'msisdn AS subscriber', 'msisdn_counterpart', 'network', 'operator_code', 'outgoing', 'tac']
EventTableSubset: hour_slices:<HourSlice: [HourInterval(start_hour=<flowmachine.core.hour_slice.MissingHourAndMinutesTimestamp object at 0x115d21520>, stop_hour='00:00', freq='day', weekday=None), HourInterval(start_hour='23:00', stop_hour=<flowmachine.core.hour_slice.MissingHourAndMinutesTimestamp object at 0x115d212e0>, freq='day', weekday=None)]>
EventTableSubset: hours:[0, 23]
EventTableSubset: sqlalchemy_table:events.calls
EventTableSubset: start:2016-01-01 00:00:00
EventTableSubset: stop:2016-01-02 00:00:00
EventTableSubset: subscriber_identifier:msisdn
EventTableSubset: subscriber_subsetter:<SubscriberSubsetterForAllSubscribers (query_id='869c2093b89e9809c7656dd19ae718ba')>
```

Specifically: `<flowmachine.core.hour_slice.MissingHourAndMinutesTimestamp object at 0x115d21520>` which doesn't have a string representation, and hence will semi-randomly vary.
