### ISSUE TITLE
GADM download URL has changed

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit#6588]
The FlowDB synthetic data generator fetches admin boundaries for a specified country from GADM:

https://github.com/Flowminder/FlowKit/blob/7130db36fdb886b8bd03913671f8109963cb0571/flowdb/testdata/bin/9900_ingest_synthetic_data.sh#L56

The GADM download URL has changed - should be 'https://geodata.ucdavis.edu/gadm/gadm3.6/shp/gadm36_${COUNTRY}_shp.zip' for GADM v3.6.

Additionally, the latest GADM version is 4.1 - I can't think of any reason we wouldn't want to update to the latest version.

**Comment by greenape** [comment]
See also #3100
