### ISSUE TITLE
Quick install instructions are insufficient

### ISSUE THREAD

**Issue by jch1g10** [Flowminder/FlowKit#688]
As of #610, `docker-compose.yml` requires `development_environment` to be sourced (or the environment variables otherwise set) before running `docker-compose up`. The [quick install instructions](https://flowminder.github.io/FlowKit/install/#quick-install) have not been updated to reflect this.

Rather than instructing a user to download and source `development_environment` before docker-composing, it would seem preferable to provide either a bash script which would set the env vars, download the compose file and spin everything up, or a demo `docker-compose` file in which the env vars are already set (this links in with #614).

While we're on the subject, we should also review the [dev](https://flowminder.github.io/FlowKit/install/#developer-install) and [production](https://flowminder.github.io/FlowKit/install/#production-install) install instructions, to ensure they are correct and sufficient.

**Comment by greenape** [comment]
If it weren't for the `build` sections in the compose file, one could simply do this:

```bash
#!/usr/bin/env bash

set -a
source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Flowminder/FlowKit/master/development_environment)"
export DOCKER_FLOWDB_HOST=flowdb_testdata
set +a
curl -s https://raw.githubusercontent.com/Flowminder/FlowKit/master/docker-compose.yml | docker-compose -f - up flowdb_testdata flowapi flowmachine flowauth query_locker
```

And get people to curl-exec that.

**Comment by maxalbert** [comment]
Should also review the instructions about [Setting up a development environment](https://flowminder.github.io/FlowKit/dev_environment_setup/) - possible that the changes in #610 have affected those too.
