### ISSUE TITLE
`flowmachine.connect()` creates multiple loggers if connection to flowdb failed

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#691]
**Describe the bug**
When calling `flowmachine.connect()` multiple times without flowdb being available (so that the call to `connnect()` fails), this creates multiple duplicate loggers (and might also have other duplicate effects).

**Product**
Flowmachine.

**Version**
Latest master (`0.6.1+107.gfd229bf8`).

**To Reproduce**
Ensure that flowdb is *not* running.

Then run:
```python
import flowmachine
import sqlalchemy
from time import sleep

for i in range(1, 6): 
    try: 
        flowmachine.connect()
        break
    except sqlalchemy.exc.OperationalError: 
        print(f"Failed to connect to flowdb. Retrying (attempt {i}/5)") 
        sleep(1)
```
The output shows that multiple duplicate loggers are created:
```
Logger created with level DEBUG
Failed to connect to flowdb. Retrying (attempt 1/5)
Logger created with level DEBUG
Logger created with level DEBUG
Failed to connect to flowdb. Retrying (attempt 2/5)
Logger created with level DEBUG
Logger created with level DEBUG
Logger created with level DEBUG
Failed to connect to flowdb. Retrying (attempt 3/5)
Logger created with level DEBUG
Logger created with level DEBUG
Logger created with level DEBUG
Logger created with level DEBUG
Failed to connect to flowdb. Retrying (attempt 4/5)
Logger created with level DEBUG
Logger created with level DEBUG
Logger created with level DEBUG
Logger created with level DEBUG
Logger created with level DEBUG
Failed to connect to flowdb. Retrying (attempt 5/5)
```

**Expected behavior**
Only a single logger should be created. More generally, `flowmachine.connect()` should not do anything other than trying to establish the connection to `flowdb`. Any other initialisation code should be run separately.

**Comment by greenape** [comment]
Hah. Yes. Isn't actually creating multiple loggers - just adding lots of stream handlers to the same one. 

`flowmachine.connect` doing nothing aside from connecting to flowdb I'm not convinced by, you still need something to start the Redis connection and the thread pool. `connect` is maybe a bad name for the function though.
