### ISSUE TITLE
Explicitly state installation requirements in docs

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#703]
The docs should have a clear and easy-to-discover section about installation requirements (probably on the [How to Install FlowKit](https://flowminder.github.io/FlowKit/install/) page).

This should mention the minimum (& recommended) versions of Python and docker, for both users and developers.

It should also have a brief overview (diagram?) of the architecture, so that users understand under which circumstances they only need to care about installing FlowClient, vs. all FlowKit components.

It would be good to accompany this with a couple of "usage scenarios" - for example, demonstrating how a user would connect to an already-existing production FlowKit installation vs. if they want to set up the demo system on their own laptop.

**Comment by greenape** [comment]
FlowClient & FlowMachine (client): Python 3.6
FlowMachine server: Python 3.7
FlowKit: Docker 17.12.0, compose 1.21.0
