### ISSUE TITLE
"Copy token" button in FlowAuth frontend

### ISSUE THREAD

**Issue by jch1g10** [Flowminder/FlowKit#704]
Now that we have exposed more queries through the API, the API token strings are getting quite long and no longer fit within the box within which they are displayed in the FlowAuth frontend.

This increases the risk of a user only copying part of the token, if they don't realise that the whole token is not visible without scrolling.

Clearly a triple-click will always select the whole token, but if the box is partially scrolled so that the header and signature are not visible then a double-click will appear to have selected everything when in reality only the payload is selected.

A "copy token" button at the top of the box would remove this risk.

**Comment by greenape** [comment]
Maybe also a download button?

**Comment by greenape** [comment]
I think actually better if the UI changes a little more, and you have three buttons instead of the current one - copy, download, view.

**Comment by BhavinPanch** [comment]
I have managed to add those changes. 
![Screenshot 2019-05-21 at 14 58 32](https://user-images.githubusercontent.com/42155258/58104734-29c0c980-7bdd-11e9-932b-606caa7eab36.jpg)
