### ISSUE TITLE
Sporadic test fails in flowauth front end tests

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#719]
Eg https://circleci.com/gh/Flowminder/FlowKit/49206

Think I’ve worked out what causes these - cypress and the app aren’t in state lockstep in the way one expects from python testing. So, if the result of the _previous_ test hasn’t finished happening in the app, strange things occur.

**Comment by josh-gree** [comment]
Is it maybe just a case of adding a `wait` in the `beforeEach` after you do the `get` like they do here -> https://xebia.com/blog/cypress-dealing-with-flaky-tests/

**Comment by greenape** [comment]
The reason this happens:

1. Cypress clears all cookies after each test
1. FlowAuth's ui uses async promise chains in some places
1. If a test does end up waiting for a properly 'finished' state (no pending promises), promises may start to be resolved _after_ cookies have been cleared, resulting in a 401 coming back and an error being raised in the beforeEach of the _next test_.
