### ISSUE TITLE
More reliable method of checking for airflow startup in flowetl tests

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#750]
Spinning out from a comment on PR #744: the `flowetl` test fixtures currently use `sleep()` to wait for startup of airflow. It would be good to avoid this and switch to a more reliable way of checking that the container is started up and available.

**Comment by greenape** [comment]
There are three solutions to this that I've seen in docker-world:

- Healthcheck (not as supported as one might like by Docker's own tooling, e.g. won't get accounted for if using depends on in compose)
- Container shouldn't be responsive on any port until it is _actually ready_ and you fail-and-repeat until it is
- You fail-and-repeat until whatever you wanted to do works, and eventually give up

Docker advocate solution three fwiw.

**Comment by maxalbert** [comment]
Yeah, I feel that we should strive for our own containers to adhere to solution 2, but solution 3 is the only really feasible one when interacting with containers that we don't fully control (and it's still good practice in any case even when interacting with a container that hopefully implements no. 2 because it adds more resilience).
