### ISSUE TITLE
Which Airflow image to use?

### ISSUE THREAD

**Issue by josh-gree** [Flowminder/FlowKit#765]
FlowETL is currently using `greenape/docker-airflow` container for airflow which uses most recent version of airflow `10.1.3` and works with python `3.7`. The most widely used airflow image is `puckel/docker-airflow` but this is not yet using `10.1.3` or python `3.7` - there is an issue and PR but not as yet merged.

https://github.com/puckel/docker-airflow/pull/358 

When this is merged we should swap back.

**Comment by greenape** [comment]
Puckel's image is now on 10.1.3

**Comment by josh-gree** [comment]
Cool will change it!

**Comment by greenape** [comment]
There's now a PR open (https://github.com/puckel/docker-airflow/pull/385) which will bump puckel's image to python 3.7, at which point there's no reason to use my one.

**Comment by rilma** [comment]
Puckel has approved [my PR](https://github.com/puckel/docker-airflow/pull/385) so we have it in Python 3.7
Additionally, Airflow has been bumped to 1.10.4 so go ahead and refresh your code!
