### ISSUE TITLE
'quick-start.sh stop' doesn't remove volumes

### ISSUE THREAD

**Issue by jch1g10** [Flowminder/FlowKit#775]
The `quick_start.sh` script can be used to spin up a full demo FlowKit on a clean system (i.e. no prior FlowKit components present). `bash quick_start.sh stop` should reverse this process, and remove all Docker containers and volumes created.

At the moment, `bash quick_start.sh stop` runs `docker-compose down`, which removes the containers but not volumes. If the user spins up FlowKit with the FlowDB synthetic data image, and then stops it with `bash quick_start.sh stop`, this will leave behind a ~3.5GB anonymous volume which they may not be aware of. Repeatedly spinning up and down with this script will create a new volume each time.

The quick-start script should run `docker-compose down -v`, to remove the FlowDB volume along with the containers.

**Comment by maxalbert** [comment]
Is this a docker-internal volume (as oppose to a bind mount) that gets created and then sticks around?

**Comment by greenape** [comment]
Postgres base image has a built in volume for the data directory.
