### ISSUE TITLE
FlowClient 'modal_location_from_dates' should accept a sequence of dates

### ISSUE THREAD

**Issue by jch1g10** [Flowminder/FlowKit#809]
Currently, the FlowClient `modal_location_from_dates` function takes parameters `start_date` and `end_date` and implicitly constructs a `pandas.date_range` from these parameters. A `date_range` is inclusive of both limits, which is inconsistent with FlowMachine queries which accept a start date and end date, where the end date is excluded.

We could modify `modal_location_from_dates` to construct a `date_range` with upper limit `end_date - (1 day)`, but it may make more sense to explicitly accept a list of dates instead of the two limits. It's not a big extra step to require the user to construct a pandas `date_range` first (particularly if we have worked examples showing this), and this would allow greater flexibility in creating modal location queries for non-consecutive sets of dates.

**Comment by maxalbert** [comment]
Agreed, it would make `modal_location_from_dates` both more flexible and more transparent if we require an explicit list of dates.

The question of whether or not the end date should be included in FlowMachine requires a separate discussion imho, but the good thing about your suggested change is that it would also make FlowClient less dependent on whatever FlowMachine does internally.

**Comment by greenape** [comment]
Isn’t that exactly the point of the regular modal location function? 🤔

**Comment by jch1g10** [comment]
The regular modal location function takes an explicit list of location query specs, which have to be created separately. I suppose it comes down to the question of whether
```
pd.date_range(start_date, end_date)
```
is sufficiently simpler than
```
[
    flowclient.daily_location(
        date=date, aggregation_unit="admin3",method="last"
    )
    for date in pd.date_range(start_date, end_date)
]
```
to warrant a separate function.

**Comment by jch1g10** [comment]
@greenape I think you're right that this wouldn't be sufficiently different from the regular `modal_location` function. In which case this reduces to the issue of inconsistent `end_date` behaviour.

As @maxalbert pointed out, this may require a separate discussion, so I'll open a separate issue.
