### ISSUE TITLE
CircleCI build is not very fork friendly

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#88]
At present, the build config for CircleCI will require manual tweaking to be runnable if you're forking the project. This is _mostly_ because of the pushing/pulling from docker, but also applies to the docs deploy and flowclient wheel push.

It would be great if we could make the config a bit more generic (e.g. replace the flowminder/flowkit specific docker cloud repos with env var driven ones), to simplify setup for people who want to work with the codebase.

**Comment by greenape** [comment]
I'm wondering if shifting some of the workflow that lives on Circle to GitHub Actions would help with this?

**Comment by maxalbert** [comment]
Interesting, might be worth exploring.

One caveat is that GitHub Actions [are currently beta](https://developer.github.com/actions/) and they say "you should avoid using it for high-value workflows and content during this beta period". So we should be careful not to invest too much time into building a solution that may go away (or need considerable rework) again in the future. But I'm all for exploring what the benefits might be if you feel it's worth it.
