### ISSUE TITLE
Occasional flowauth frontent test failures

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#965]
@greenape is probably aware of this but sometimes the flowauth frontent tests fail ([example](https://circleci.com/workflow-run/d4ed0685-1971-4aec-8e83-cd746be30c06)). Not sure if this is the same as previous issues but thought I'd open an issue so that we can track it.

**Comment by greenape** [comment]
A'ight. Looks like there's various things going on here..

One is a weird pipe fail error, which I'm thinking is transient and won't be back.
One is Cypress clicking on things [too fast](https://dashboard.cypress.io/#/projects/67obxt/runs/3361/failures/ed864bed-a559-4c44-ae06-da3284391e26) (ironic, given it types slower than I do) 
One is Cypress either sporadically not sending cookies, or hitting the first page before the request which logs it in finishes and sets the cookie, so it [isn't logged in](https://dashboard.cypress.io/#/projects/67obxt/runs/3363/failures/ef6bd0bb-a59b-44e7-873b-11078aa043b5)
